# Generated by Django 3.2.5 on 2021-07-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_ID', models.IntegerField()),
                ('PATIENT_NAME', models.CharField(max_length=200)),
                ('EVENT_TYPE', models.CharField(max_length=100)),
                ('EVENT_VALUE', models.IntegerField()),
                ('EVENT_UNIT', models.CharField(max_length=100)),
                ('EVENT_TIME', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'EVENT_TIME',
            },
        ),
    ]
